version: "3.8"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    networks:
      - media_network
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - plex_config:/config
      - /home/user/media/tv:/tv
      - /home/user/media/movies:/movies
    ports:
      - 32400:32400
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - sonarr_config:/config
      - /home/user/media/tv:/tv
      - /home/user/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - radarr_config:/config
      - /home/user/media/movies:/movies
      - /home/user/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - media_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - overseerr_config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - media_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - bazarr_config:/config
      - /home/user/media/tv:/tv
      - /home/user/media/movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    networks:
      - media_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - nzbget_config:/config
      - /home/user/media/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - media_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: 1000:1000
    networks:
      - media_network
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

networks:
  media_network:
    name: media_network

volumes:
  plex_config:
  sonarr_config:
  radarr_config:
  overseerr_config:
  bazarr_config:
  nzbget_config:
  prowlarr_config: