version: "3.8"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    networks:
      - media_network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM:-}
    volumes:
      - plex_config:/data/config
      - tv_data:/data/tv
      - movies_data:/data/movies
    ports:
      - 32400:32400
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media_network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - sonarr_config:/data/config
      - tv_data:/data/tv
      - downloads_data:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media_network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - radarr_config:/data/config
      - movies_data:/data/movies
      - downloads_data:/data/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - media_network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - overseerr_config:/data/config
    ports:
      - 5055:5055
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - media_network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - bazarr_config:/data/config
      - tv_data:/data/tv
      - movies_data:/data/movies
    ports:
      - 6767:6767
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    networks:
      - media_network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - sabnzbd_config:/data/config
      - downloads_data:/data/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - media_network
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - prowlarr_config:/data/config
    ports:
      - 9696:9696
    restart: unless-stopped

  buildarr:
    image: callum027/buildarr:latest
    restart: unless-stopped
    container_name: buildarr
    networks:
      - media_network
    volumes:
      - ./buildarr:/config
      - ./buildarr-secret.yml:/config/secrets.yaml:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}

networks:
  media_network:
    name: media_network

volumes:
  plex_config:
  sonarr_config:
  radarr_config:
  overseerr_config:
  bazarr_config:
  sabnzbd_config:
  prowlarr_config:
  tv_data:
  movies_data:
  downloads_data: