version: "3.8"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    networks:
      - media_network
    environment:
      - VERSION=docker
    volumes:
      - plex_config:/data/config
      - tv_data:/data/tv
      - movies_data:/data/movies
    ports:
      - 32400:32400
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media_network
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - sonarr_config:/data/config
      - tv_data:/data/tv
      - downloads_data:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media_network
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - radarr_config:/data/config
      - movies_data:/data/movies
      - downloads_data:/data/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - media_network
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - overseerr_config:/data/config
    ports:
      - 5055:5055
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - media_network
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - bazarr_config:/data/config
      - tv_data:/data/tv
      - movies_data:/data/movies
    ports:
      - 6767:6767
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    networks:
      - media_network
    environment:
      - TZ=Europe/Amsterdam
      - NZBGET_USER=nzbget
      - NZBGET_PASS=tegbzn6789
    volumes:
      - nzbget_config:/data/config
      - downloads_data:/data/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - media_network
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - prowlarr_config:/data/config
    ports:
      - 9696:9696
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    networks:
      - media_network
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

networks:
  media_network:
    name: media_network

volumes:
  plex_config:
  sonarr_config:
  radarr_config:
  overseerr_config:
  bazarr_config:
  nzbget_config:
  prowlarr_config:
  tv_data:
  movies_data:
  downloads_data: