# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  series:
    base_url: !secret sonarr_base_url
    api_key: !secret sonarr_api_key
    quality_definition:
      type: series

radarr:
  movies:
    base_url: !secret radarr_base_url
    api_key: !secret radarr_api_key
    quality_definition:
      type: movie
      preferred_ratio: 0.5